name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          mkdir dist
          flutter build apk --release --split-per-abi
          cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk dist/app-armeabi-v7a-release.apk
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk dist/app-arm64-v8a-release.apk
          cp build/app/outputs/flutter-apk/app-x86_64-release.apk dist/app-x86_64-release.apk

      - name: Build APK(Universal)
        run: |
          flutter build apk --release
          cp build/app/outputs/flutter-apk/app-release.apk dist/app-universal-release.apk

      - name: Upload APK(ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: app-arm64-v8a-release.apk
          path: dist/

      - name: Upload APK(ARMv7)
        uses: actions/upload-artifact@v4
        with:
          name: app-armeabi-v7a-release.apk
          path: dist/

      - name: Upload APK(x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: app-x86_64-release.apk
          path: dist/
          
      - name: Upload APK(Universal)
        uses: actions/upload-artifact@v4
        with:
          name: app-universal-release.apk
          path: dist/    

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Download Artifact(ARM64)
        uses: actions/download-artifact@v4
        with:
          name: "app-arm64-v8a-release.apk"
          path: dist/

      - name: Download Artifact(ARMv7)
        uses: actions/download-artifact@v4
        with:
          name: "app-armeabi-v7a-release.apk"
          path: dist/

      - name: Download Artifact(x86_64)
        uses: actions/download-artifact@v4
        with:
          name: "app-x86_64-release.apk"
          path: dist/
     
      - name: Download Artifact(Universal)
        uses: actions/download-artifact@v4
        with:
          name: "app-universal-release.apk"
          path: dist/    
          
      - name: Fetch Version
        run: |
          sudo snap install yq
          nbgui_version=$(yq eval '.version' pubspec.yaml)
          echo "NBGUI_VERSION=$nbgui_version" >> $GITHUB_ENV
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NBGUI_VERSION }}
          body_path: RELEASE_CHANGELOG.md
          prerelease: false
          draft: false
          generate_release_notes: true
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          files: |
            dist/app-armeabi-v7a-release.apk
            dist/app-arm64-v8a-release.apk
            dist/app-x86_64-release.apk
            dist/app-universal-release.apk